# Config for Travis CI, tests powered by DepHell.
# https://travis-ci.org/
# https://github.com/dephell/dephell

language: python
dist: xenial

before_install:
  # show a little bit more information about environment
  - sudo apt-get install -y tree
  - env
  - tree
  - ls /opt/python
  # install DepHell
  # https://github.com/travis-ci/travis-ci/issues/8589
  - curl -L dephell.org/install | /opt/python/$TRAVIS_PYTHON_VERSION/bin/python
  - dephell inspect self
install:
  - dephell venv create --env=$ENV --python="/opt/python/$TRAVIS_PYTHON_VERSION/bin/python"
  - dephell deps install --env=$ENV
script:
  - dephell venv run --env=$ENV

matrix:
  include:

    - python: "3.7"
      env: ENV=pytest
    - python: "3.6.7"
      env: ENV=pytest
    - python: "3.5"
      env: ENV=pytest
    - python: "3.4"
      env: ENV=pytest
    - python: "2.7"
      env: ENV=pytest

    - name: lint
      python: "3.7"
      env: ENV=main

    # https://github.com/igorshubovych/markdownlint-cli
    - name: markdown lint
      language: generic
      install:
        - npm install -g markdownlint-cli
      script:
        - bash -c "markdownlint --config markdownlint.json **/*.md"

    - python: "3.7"
      env: ENV=docs
